### ISSUE TITLE
Feature request/ticker combat darkeing fade thingy?

### ISSUE THREAD

**Issue by Theguyxd** [rgd87/NugEnergy#15]
Hi, I'd like to start off by saying that I love this addon and I think it's a must for any version of Classic. Now, what I'd really like is for the energytick bar to not fade to a darker color when out of combat. What I'm talking about here is not the total alpha of the bar but the "darkening" effect that happens when combat ends. At least I think it's related to combat somehow. I hope I'm clear enough here. If this is something that the author does not want to add or does not have time to add then I'd really like to know what I can search for and change in the lua to make it happen myself. Thanks again! 

EDIT: I shouldn't have said that it was linked to combat. More like that the bar darkens once I do not get energy form the tick. Or at least something similar to that?

**Comment by d87** [comment]
Ok, update and uncheck "Recolor when capped"

**Comment by Theguyxd** [comment]
Holy! That was exactly what I was talking about. Thank you very much and have a happy new year!
