### ISSUE TITLE
border around text?

### ISSUE THREAD

**Issue by ixobelle** [rgd87/NugEnergy#16]
My only addition to this addon would be if we could have a border around the text itself. I have it "up above" (using the fantastic X, Y displacement sliders), but a simple stroke checkbox would be huge.

![NEN](https://github.com/rgd87/NugEnergy/assets/6091037/802d505d-b825-4a03-9bcc-26afefe4738d)

**Comment by d87** [comment]
Alright, update to 10.2.3, and I assume you were talking about text outline
