### ISSUE TITLE
BCC: Reset Energy Tick on Druid Catform shift

### ISSUE THREAD

**Issue by Larnak1** [rgd87/NugEnergy#9]
Hi!

Currently in BCC energy ticks reset whenever a druid shifts into Cat Form. Nug Energy, on the other hand, continues with the original timing, and only resets when the next energy tick occurs. It would be great if the reset would already occur when the form is shifted.

Details about the energy regen for Druids in BCC can be found here:
https://pastebin.com/WVh1VP45

Cheers! 
PS: Great Addon :)

**Comment by d87** [comment]
Done, but did blizzard eventually removed regen in human form in BCC?

**Comment by Larnak1** [comment]
Nice :)

I don't know, sorry :( The linked summary already goes beyond my original knowledge. I only saw that it's no longer benefitial to shift shortly before an energy tick, as the tick always resets - and found that explanation afterwards.

**Comment by Larnak1** [comment]
Looks like this needs to be reverted, Blizzard is changing the energy regen for cats:
https://tbc.wowhead.com/news/burning-crusade-classic-feral-druid-energy-change-coming-with-regional-restarts-323104

**Comment by d87** [comment]
already done

**Comment by Larnak1** [comment]
Ah sorry, should have checked releases first
